#!/bin/bash
CURRENT_DIR=$(dirname $(realpath $0))
PROJECT_DIR=$(dirname $CURRENT_DIR)
CONTAINER_NAME=gdrnpp_test
IMAGE_NAME=shihaoqi/gdrnpp:latest

if [ "$(docker ps -aq -f name=$CONTAINER_NAME)" ]; then
    docker start $CONTAINER_NAME
    docker exec -it $CONTAINER_NAME /bin/bash
else
    #-v $CURRENT_DIR:
    echo $PROJECT_DIR
    docker run -it \
        --gpus '"device=5,6,7,8,9"' \
        --name $CONTAINER_NAME \
        $IMAGE_NAME \
        /bin/bash
fi
